name:                zpf-typesafe-parser
version:             0.1.0.0
github:              "Day1721/zpf-typesafe-parser"
license:             BSD3
author:              "Marek Puzyna"
maintainer:          "puzynamarek97@gmail.com"
copyright:           "2019 Marek Puzyna"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Day1721/zpf-typesafe-parser#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.13 && < 3
- megaparsec >= 7.0.4 && < 8
- reflection >= 2.1.4 && < 3

library:
  source-dirs: src

ghc-options:
  -Werror=incomplete-patterns
  -Werror=missing-methods

executables:
  zpf-typesafe-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zpf-typesafe-parser

tests:
  zpf-typesafe-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zpf-typesafe-parser
